#!/bin/bash

Normal_pkg_lst=(make python kvm qemu qemu-kvm  python-libvirt gettext python-urlgrabber python-gtk-vnc virtinst nfs-common virt-top kvm-ipxe vlan vim libnl-dev gcc make pkg-config libxml2-dev libgnutls-dev libdevmapper-dev libcurl4-gnutls-dev python-dev libyajl-dev aptitude linux-headers-3.2.0-29-generic  openssh-server cgroup-bin libpciaccess-dev)

############################################################################################################################
 
#Function to check whther the network gateway is pingable or not
Chk_Gateway()
{
        ping -q -c5 NETWORK_GATEWAY_IP > /dev/null

        if test $? -ne 0;then
                echo "NETWORK GATEWAY IS NOT REACHABLE!!!"
                exit 1
        fi
}


#Function that install all the packages packages
Instl_Pkgs()
{	
	echo "Installing some useful packages"
	echo "==============================="

	Pkg_lst=()
	Pkg_lst=${Normal_pkg_lst[@]}

	for pkg_multi_vrsn in ${Pkg_lst[@]}; do

                pkg_status=0
                pkg_multi_vrsn=(`echo $pkg_multi_vrsn | tr ":" " "`)

                for pkg in ${pkg_multi_vrsn[@]}; do

                                echo "Installing Package: $pkg.................."
                                DEBIAN_FRONTEND=noninteractive apt-get -y install $pkg --force-yes

                done


	done
	
	echo "Packages Installed Successfully..................................."
}


Enbl_Modules()
{

	echo "Enabling KVM support"

	modprobe kvm
	modprobe kvm_intel

	cd /root
	libvirt_output=`ls BAADAL_REPO_INSTALL/baadalinstallation | grep "libvirt"`

	if test -z $libvirt_output; then
        	echo "libvirt tar is not found. Please retry SCP"
        	exit 1
	fi

	echo "Installing libvirt-1.0.0"

	tar -xvzf BAADAL_REPO_INSTALL/baadalinstallation/libvirt-1.0.0.tar.gz
	cd libvirt-1.0.0
	./configure --prefix=/usr --localstatedir=/var --sysconfdir=/etc --with-esx=yes
	make
	make install
	/etc/init.d/libvirt-bin restart
	
	mkdir -p LOCAL_MOUNT_POINT
	mount STORAGE_SERVER_IP:STORAGE_DIRECTORY LOCAL_MOUNT_POINT
	echo "If you have done all the steps correctly, Congo!!!"
}

############################################################################################################################

apt-get update && apt-get -y upgrade
Chk_Gateway
Instl_Pkgs
Enbl_Modules
hostname baadal-host
echo "baadal-host" > /etc/hostname
reboot


