ROOT=$PWD
BAADAL_LOCAL_DIR=~/.baadal

BIN=$BAADAL_LOCAL_DIR/bin
UTILS=/baadal/baadal/baadaltesting/sandbox/utils
UTILS_LOCAL=$BAADAL_LOCAL_DIR/utils
DISKS=$BAADAL_LOCAL_DIR/disks
LOGS=$BAADAL_LOCAL_DIR/logs
TEMP=$BAADAL_LOCAL_DIR/temp
CONFIG=$BAADAL_LOCAL_DIR/config
SRC=$ROOT/src
NAT=$SRC/nat
CONTROLLER=$SRC/controller
PXE=$SRC/pxe_dhcp
CFENGINE=$SRC/cfengine
MYSQL=$SRC/mysql
CONFIGURE=$SRC/constants.sh

UBUNTU=$UTILS/ubuntu.iso
LIBVIRT=libvirt-1.2.1
LIBVIRT_TAR=$UTILS/$LIBVIRT.tar.gz
LIBVIRTPYTHON=libvirt-python
LIBVIRTPYTHON_DIR=$UTILS/$LIBVIRTPYTHON
VIRTMANAGER=virt-manager-0.10.0
VIRTMANAGER_TAR=$UTILS/$VIRTMANAGER.tar.gz

ECHO_PROGRESS="echo -e -n"
ECHO_OK="echo -e \"\r\033[K[\e[0;32mOK\e[0m]\t"
ECHO_ER="echo -e \"\r\033[K[\e[0;31mER\e[0m]\t"
LOG_CLEAN="rm -f $LOGS/*"
LOG_SIZE=10

INTERFACE=${INTERFACE:-eth0}

#Update this in OVS_NET_XML too
OVS_BRIDGE_INTERNAL=baadal-br-int
OVS_NET_INTERNAL=ovs-net
OVS_NET_XML_INTERNAL=$BIN/ovs-net.xml
DHCP_BRIDGE_INTERNAL=dhcp-br-int

#Because we use a mask of 255.255.0.0
NETWORK_BITS=16
VLAN_START=1
VLAN_END=255
VLAN_NETMASK=255.255.255.0

PXE_DISK=$DISKS/pxe_dhcp.img
PXE_SPACE=10
PXE_ARCH=x86_64
PXE_NAME=baadal_pxe_dhcp
PXE_HOSTNAME=baadal-pxe-dhcp # Should match in ks.cfg
PXE_RAM=1028
PXE_VCPUS=2
PXE_ISO=$UTILS_LOCAL/ubuntu.pxe_dhcp.iso
PXE_KICKSTART=$BIN/ks.pxe_dhcp.cfg
PXE_TRANSFER=$BIN/transfer.pxe_dhcp/
PXE_KS=$PXE/ks.cfg
PXE_INTERFACE=${PXE_INTERFACE:-eth0}

CFENGINE_DISK=$DISKS/cfengine.img
CFENGINE_SPACE=10
CFENGINE_ARCH=x86_64
CFENGINE_NAME=baadal_cfengine
CFENGINE_HOSTNAME=baadal-cfengine # Should match in ks.cfg
CFENGINE_RAM=1028
CFENGINE_VCPUS=2
CFENGINE_ISO=$UTILS_LOCAL/ubuntu.cfengine.iso
CFENGINE_KICKSTART=$BIN/ks.cfengine.cfg
CFENGINE_TRANSFER=$BIN/transfer.cfengine/
CFENGINE_KS=$CFENGINE/ks.cfg
CFENGINE_INTERFACE=${CFENGINE_INTERFACE:-eth0}

MYSQL_DISK=$DISKS/mysql.img
MYSQL_SPACE=10
MYSQL_ARCH=x86_64
MYSQL_NAME=baadal_mysql
MYSQL_HOSTNAME=baadal-mysql # Should match in ks.cfg
MYSQL_RAM=1028
MYSQL_VCPUS=2
MYSQL_ISO=$UTILS_LOCAL/ubuntu.mysql.iso
MYSQL_KICKSTART=$BIN/ks.mysql.cfg
MYSQL_TRANSFER=$BIN/transfer.mysql/
MYSQL_KS=$MYSQL/ks.cfg
MYSQL_INTERFACE=${MYSQL_INTERFACE:-eth0}

CONTROLLER_DISK=$DISKS/controller.img
CONTROLLER_SPACE=10
CONTROLLER_ARCH=x86_64
CONTROLLER_NAME=baadal_controller
CONTROLLER_HOSTNAME=baadal-controller # Should match in ks.cfg
CONTROLLER_RAM=1028
CONTROLLER_VCPUS=2
CONTROLLER_ISO=$UTILS_LOCAL/ubuntu.controller.iso
CONTROLLER_KICKSTART=$BIN/ks.controller.cfg
CONTROLLER_TRANSFER=$BIN/transfer.controller/
CONTROLLER_KS=$CONTROLLER/ks.cfg
CONTROLLER_INTERFACE=${CONTROLLER_INTERFACE:-eth0}

MAC_CONTROLLER=52:52:00:01:15:02
MAC_NAT=52:52:00:01:15:03
MAC_PXE=52:52:00:01:15:04
MAC_CFENGINE=52:52:00:01:15:05
MAC_MYSQL=52:52:00:01:15:06
MAC_HOST_3=52:52:00:01:15:07
MAC_HOST_HELPER=MAC_HOST_${HOST_ID}
MAC_HOST=${!MAC_HOST_HELPER}


NETWORK_INTERNAL_IP_NAT=${NETWORK_INTERNAL_IP_NAT:-172.16.0.3}
